### ISSUE TITLE
Rename application menu label

### ISSUE THREAD

**Issue by ioannedelea** [harborsiem/WindowsRibbon#5]
Is there any way you can rename the application menu from the standard "File" to anything else?

**Comment by harborsiem** [comment]
@ioannedelea
You can't rename the application menu standard "File" (or the Windows language dependent name for "File"). It is fixed by Microsoft design. In Windows 7 there was an Image at the application menu, but this changed to "File" since Windows 8.
See [applicationmenu](https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-controls-applicationmenu)

**Comment by ioannedelea** [comment]
Thank you! I also tried with localization, but for some reason Thread.CurrentThread.CurrentCulture and   Thread.CurrentThread.CurrentUICulture doesn’t force the set localization on the app. I also tried with your sample (“de-De”) but for some reason the File label is not translated. 

Also thank you for your hard work!

**Comment by harborsiem** [comment]
The File label is only translated when you change the language in your Windows system. This is possible when you use a Windows Professional version, but I am not sure if it is possible with the Home version.

**Comment by ioannedelea** [comment]
Ok, that is unfortunate. I’ll try and post this issue to the Microsoft people, although I doubt I’ll have any response to it. Thanks again!
